services:
    # Jenkins based on custom image with specified plugins
    jenkins_controller:
        image: jenkins/controller:local
        container_name: jenkins_controller
        volumes:
            - ./jenkins_home_local:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "80:8080"
            - "60000:60000"

# allow jenkins agents and any additional containers to communicate within this network
networks:
    default:
        name: jdn
